### ISSUE TITLE
Hold [Left Alt] to focus key bind doesn't work on the forge version

### ISSUE THREAD

**Issue by coolprogramer234** [TimStewartJ/TheMightyArchitectury#1]
when holding down the key bind for the menu it doesn't let me access the menu and pressing the button doesn't work either

**Comment by TimStewartJ** [comment]
Hmm I'm not able to replicate this behavior. Do you have any other mods installed? Is Left Alt conflicting with another keybind?

**Comment by coolprogramer234** [comment]
i have a lot of create addons but i rebounded it to a key that wasn't bound

**Comment by TimStewartJ** [comment]
I think I see what was happening. Try this build and let me know if it works now: https://github.com/TimStewartJ/TheMightyArchitectury/releases/tag/v0.6.1-beta.1

**Comment by coolprogramer234** [comment]
thx it works
