### ISSUE TITLE
multiplayer?

### ISSUE THREAD

**Issue by ByteSpencer** [TimStewartJ/TheMightyArchitectury#8]
hello! i know the support for this may be no longer activeeee but i was wondering if this was only for single player? i tried using this on my server and it just prompts me with a message saying 
![Screenshot 2023-05-06 042712](https://user-images.githubusercontent.com/132726341/236612798-d53e2c41-6acb-47cd-9137-6f6ec2a0b1bb.png)

help/ an answer would be appreciated ty

**Comment by TimStewartJ** [comment]
This should be fixed in the latest release available on modrinth now!
